{% set version = "0.11.0" %}

package:
  name: lintrunner-adapters
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lintrunner-adapters/lintrunner_adapters-{{ version }}.tar.gz
  sha256: 18bef20e795133995314db26bbc5e9290ad18adf5d7150d935fe8cb879200c08

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - |-
      {{ PYTHON }} -c "import os, pathlib; sp = pathlib.Path(os.environ['SP_DIR']); [(sp / f).unlink() for f in ['LICENSE']]"
  entry_points:
    - lintrunner_adapters = lintrunner_adapters.__main__:cli

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.7
  run:
    - click >=8.1.3,<9.0.0
    - python >=3.7.0

test:
  imports:
    - lintrunner_adapters
  commands:
    - pip check
    - lintrunner_adapters --help
  requires:
    - pip

about:
  home: https://github.com/justinchuby/lintrunner-adapters
  summary: Adapters and tools for lintrunner
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
