{% set version = "0.12.6" %}

package:
  name: lintrunner-adapters
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/lintrunner-adapters/lintrunner_adapters-{{ version }}.tar.gz
  sha256: 3ba6a449733d851dc73a7f28bbf7bd14c5e618a0bcd8c016c5f2b4c77e19c4ba

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    - |-
      {{ PYTHON }} -c "import os, pathlib; sp = pathlib.Path(os.environ['SP_DIR']); [(sp / f).unlink() for f in ['LICENSE']]"
  entry_points:
    - lintrunner_adapters = lintrunner_adapters.__main__:cli

requirements:
  host:
    - pip
    - poetry-core <2
    - python {{ python_min }}
  run:
    - click >=8.1.3,<9.0.0
    - python >={{ python_min }}

test:
  imports:
    - lintrunner_adapters
  commands:
    - pip check
    - lintrunner_adapters --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/justinchuby/lintrunner-adapters
  summary: Adapters and tools for lintrunner
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
